DEFAULT_TIMEOUT = 10.0
DEFAULT_NAMESPACE = 'default'
VISIBILITY_PRIVATE = 'private'
VISIBILITY_PUBLIC = 'public'
USER_AGENT_PREFIX = 'intent-bus-python'
DEFAULT_RETRIES = 2

RESULT_JSON = 'json'
RESULT_TEXT = 'text'

DEFAULT_POLL_INTERVAL = 5.0
MAX_POLL_BACKOFF = 60.0

# SDK / Protocol matching
SERVER_API_VERSION = '7.5'
SDK_VERSION_HEADER = 'X-Intent-Version'

# Transport limits
DEFAULT_POOL_SIZE = 10
RETRYABLE_SERVER_ERRORS = frozenset({429, 500, 502, 503, 504})
